# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "clgIdMrRpkuOucWwqREhumC3XZ6Rp6pcVqP+qWqzY9r5mvHyCSihZzO+KkDOcUz8FV0dMyuqOuOCzfC+YuaiQLjhkunQJP/gOpILv8Q7BTrZq045QD2gY7xklZQOHNmhUkjMLd1ayECuw4WHy0/L6JGWAF+S39DGRqKMAcdY9GkmDyeMui5OlFcKyHfGQTxCrBK0aNGHF7KRKtN7Fgywwz1R8tT7xq8sGgfX0txu9Ybdw29pj7/squarlXBhNIaFOGlfVJqMta6GZwODr8xsSISBrMugAJpPxVSqwZptMQGGz/s/MnGLszGfmx5S6Mga/bZTJweVNARG2EndgbVBcU4Vp8UxLENcroEUFXB14nzBl2tUVnWOb66vGQnvekNiRld3NCniTS1N1tNC63d24Q7XoHGI7cq6+SYA76u6ZjKTXfbsA7g4Yv5OcEot1fGktzZB6bSX9I9T9aS3BejeBlWlBCd8pmiD4ARHP9P95eWdwsJ8pbLXa4V2KjuzVz147QDGmrB1g3g4YrV6ADdLRT5TGQYuTcYbU4F1zbQSukdr3Y/X9afnN+9RMmtFf8/JdTPDDnFBj6baL6gdnjVGhX41enotCiNC3c9+oSmGvlziKo28sSeZqUs/tlFvF+1xmiTfgZPqM5IvFdPjoGZeT3cSkhTu9mjOBDgsMpV21V8="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
